//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpliLearnWebServiceClient.EmployeeServiceApp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceApp.SimplilearnEmployeeServiceSoap")]
    public interface SimplilearnEmployeeServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponse GetEmployees(SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponse> GetEmployeesAsync(SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponse AddEmployee(SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponse> AddEmployeeAsync(SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpliLearnWebServiceClient.EmployeeServiceApp.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(SimpliLearnWebServiceClient.EmployeeServiceApp.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployee", Namespace="http://tempuri.org/", Order=0)]
        public SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequestBody Body;
        
        public AddEmployeeRequest() {
        }
        
        public AddEmployeeRequest(SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string designation;
        
        public AddEmployeeRequestBody() {
        }
        
        public AddEmployeeRequestBody(string name, string designation) {
            this.name = name;
            this.designation = designation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponseBody Body;
        
        public AddEmployeeResponse() {
        }
        
        public AddEmployeeResponse(SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpliLearnWebServiceClient.EmployeeServiceApp.Employee[] AddEmployeeResult;
        
        public AddEmployeeResponseBody() {
        }
        
        public AddEmployeeResponseBody(SimpliLearnWebServiceClient.EmployeeServiceApp.Employee[] AddEmployeeResult) {
            this.AddEmployeeResult = AddEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplilearnEmployeeServiceSoapChannel : SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplilearnEmployeeServiceSoapClient : System.ServiceModel.ClientBase<SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap>, SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap {
        
        public SimplilearnEmployeeServiceSoapClient() {
        }
        
        public SimplilearnEmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplilearnEmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplilearnEmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplilearnEmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponse SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap.GetEmployees(SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public SimpliLearnWebServiceClient.EmployeeServiceApp.Employee[] GetEmployees() {
            SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest inValue = new SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest();
            inValue.Body = new SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequestBody();
            SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponse retVal = ((SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponse> SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap.GetEmployeesAsync(SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesResponse> GetEmployeesAsync() {
            SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest inValue = new SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequest();
            inValue.Body = new SimpliLearnWebServiceClient.EmployeeServiceApp.GetEmployeesRequestBody();
            return ((SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponse SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap.AddEmployee(SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest request) {
            return base.Channel.AddEmployee(request);
        }
        
        public SimpliLearnWebServiceClient.EmployeeServiceApp.Employee[] AddEmployee(string name, string designation) {
            SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest inValue = new SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest();
            inValue.Body = new SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequestBody();
            inValue.Body.name = name;
            inValue.Body.designation = designation;
            SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponse retVal = ((SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap)(this)).AddEmployee(inValue);
            return retVal.Body.AddEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponse> SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap.AddEmployeeAsync(SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest request) {
            return base.Channel.AddEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeResponse> AddEmployeeAsync(string name, string designation) {
            SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest inValue = new SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequest();
            inValue.Body = new SimpliLearnWebServiceClient.EmployeeServiceApp.AddEmployeeRequestBody();
            inValue.Body.name = name;
            inValue.Body.designation = designation;
            return ((SimpliLearnWebServiceClient.EmployeeServiceApp.SimplilearnEmployeeServiceSoap)(this)).AddEmployeeAsync(inValue);
        }
    }
}
